### ISSUE TITLE
Can't tell if this is just a me issue or

### ISSUE THREAD

**Issue by Wo-no** [BlueprintCoding/SillyTavernSimpleLauncher#6]
Cannot download anything for the life of me, it consistently tells me 'No directory found, ive reinstalled and retried for over 30 minutes to fix this, or it straight up closes the shell, cannot tell if my windows device is just being stupid or not

**Comment by BlueprintCoding** [comment]
I'm pushing a new release right now. V1.3. I fixed a lot of bugs and made it more robust.
Try that out and let me know if you are experiencing issues.

**Comment by BlueprintCoding** [comment]
@Wo-no New release page: https://github.com/BlueprintCoding/SillyTavernSimpleLauncher/releases/tag/V1.3

**Comment by Wo-no** [comment]
Yeah, still having issues, mostly with the gui refusing to open

**Comment by Wo-no** [comment]
Got it to download but i cannot figure out how to get "win32con"

**Comment by BlueprintCoding** [comment]
Newest release should fix this issue, it also has more logging to show me where it goes wrong if it doesn't work.

https://github.com/BlueprintCoding/SillyTavernSimpleLauncher/releases/tag/V1.3.3
